### ISSUE TITLE
MA error; texas_init: alloc for texas mapping 1 failed

### ISSUE THREAD

**Issue by diracs-delta** [nwchemgit/nwchem#194]
I am having trouble reproducing the output in the `examples` directory of NWChem with MPI enabled. Here is the environment I am using:

```
$ mpirun --version
mpirun (Open MPI) 4.0.3
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 9
Stepping:              1
CPU MHz:               2300.204
BogoMIPS:              4600.40
Virtualization:        AMD-V
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              5118K
NUMA node0 CPU(s):     0-3
NUMA node1 CPU(s):     4-7
```

I am on the NWChem-7.0 release.  When I invoke

```
$ mpirun -np 8 nwchem h3tr1.nw
```

inside `examples/h3`, I am met with the following error.

```
--------------------------------------------------------------------------
As of version 3.0.0, the "sm" BTL is no longer available in Open MPI.

Efficient, high-speed same-node shared memory communication support in
Open MPI is available in the "vader" BTL.  To use the vader BTL, you
can re-run your job with:

    mpirun --mca btl vader,self,... your_mpi_application
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      gellmann.scs.illinois.edu
Framework: btl
Component: sm
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  mca_bml_base_open() failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
[gellmann:09130] *** An error occurred in MPI_Init
[gellmann:09130] *** reported by process [861077505,2]
[gellmann:09130] *** on a NULL communicator
[gellmann:09130] *** Unknown error
[gellmann:09130] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[gellmann:09130] ***    and potentially your MPI job)
[gellmann.scs.illinois.edu:09124] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[gellmann.scs.illinois.edu:09124] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[gellmann.scs.illinois.edu:09124] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[gellmann.scs.illinois.edu:09124] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[gellmann.scs.illinois.edu:09124] 5 more processes have sent help message help-mpi-btl-sm.txt / btl sm is dead
[gellmann.scs.illinois.edu:09124] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[gellmann.scs.illinois.edu:09124] 3 more processes have sent help message help-mca-base.txt / find-available:not-valid
[gellmann.scs.illinois.edu:09124] 3 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:internal-failure
[gellmann.scs.illinois.edu:09124] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle

```

This is strange because on my PC (not this machine I am ssh'ed into), OpenMPI runs NWChem as expected even though it is the same version (v 4.0.3). Following OpenMPI's message, I invoked `mpirun --mca btl vader,self -np 8 nwchem h3tr1.nw`, and was met with [this message](https://github.com/diracs-delta/logs/blob/master/h3_nwchem.log). The pertinent lines are below.

```
MA error: MA_verify_allocator_stuff: 
				heap	stack
				----	-----
	checksum errors		   0	    0
	left signature errors	   0	    0
	right signature errors	   1	    0
	total bad blocks	   1	    0
	total blocks		  13	    4
[1] Received an Error in Communication: (911) 1:texas_init: alloc for texas mapping1 failed:
```

Does anybody know what could be causing this? I'm unsure of why this is the case, as I'm using the same version of OpenMPI and NWChem on both machines, except the one on this machine completely fails to run. I have no clue where to begin. Is it something unique with the CPU architecture of my machine? Or does it look like I compiled OpenMPI incorrectly?

**Comment by diracs-delta** [comment]
Oh, and also, here is the environment I compiled NWChem in.

```
#!/bin/bash

source $HOME/.bashrc

export NWCHEM_TOP=/home/davidlq2/Repositories/nwchem-7.0.0
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all"
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE

export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y

export BLASOPT="-L$HOME/.local/lib -lopenblas"
export LAPACK_LIB=-lopenblas

export BLAS_SIZE=4
export LIB_DEFINES="-DDFLT_TOT_MEM=16777216"

cd $NWCHEM_TOP/src
make -j 8 nwchem_config
make -j 8 64_to_32
make -j 8 USE_64TO32=y
```

I found a previous issue with a similar error message on the NWChem forums, but that was resolved after setting BLAS_SIZE to 4. It did not help me in my case.

**Comment by jeffhammond** [comment]
I'e never seen this error in my life, and I am inclined to believe you still have not fixed your MPI issues.  Why don't you just start over with MPICH and see if it gets better?

**Comment by diracs-delta** [comment]
@jeffhammond I think you are right. I've tested my MPI installation against a suite of other computational software, none of which really work properly. This is an issue with other software, and thus I will close this issue accordingly. I'll comment my solution (if I ever arrive to it) for future NWChem users to debug.
