### ISSUE TITLE
Wiki documentation is missing field names

### ISSUE THREAD

**Issue by hjjvandam** [nwchemgit/nwchem#75]
Since the documentation has been converted from the web-pages to Wiki pages there seem be a number of field names that are missing. For example try reading the documentation for the [parameter set](https://github.com/nwchemgit/nwchem/wiki/MD#parameter-set). It starts off with
```
set 

Specifies the use of parameter set for the molecular dynamics simulation. The topology file contains three separate parameters sets that can be used. The default for is 1.
```
According to the old web-pages it should read like:
```
set <integer iset>
Specifies the use of parameter set <iset> for the molecular dynamics simulation. The topology file contains three separate parameters sets that can be used. The default for <iset> is 1.
```
I am guessing that the HTML to Wiki tool used for the conversion interpreted anything between "<" and ">" as some HTML tag it didn't know, and simply dropped it.

**Comment by edoapra** [comment]
fixed

**Comment by hjjvandam** [comment]
That is much better. Fields like "<iset>" are now mentioned the directive example, but the "<iset>" mentioned in the associated text are still missing.

**Comment by hjjvandam** [comment]
Hang on, something is messing up now. What I meant to say is that 
```
set <integer iset>
```
comes out correctly now. The associated text still reads:
```
Specifies the use of parameter set for [...]
```
instead of 
```
Specifies the use of parameter set <iset> for [...]
```
(Somehow if I use "<" and ">" to bracket something in the issue text the thing gets stripped out).

**Comment by edoapra** [comment]
Done
