### ISSUE TITLE
pspw_md QA tests returning NaN when running on more than 24 processors

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#825]
**Describe the bug**
The pspw_md QA tests returning NaN when using more than 24 processors on tahoma using the current master branch https://github.com/nwchemgit/nwchem/commit/ccc2e41f3bb5697f0956b2dca97ebb41088ca130

**Describe settings used**
ARMCI_NETWORK=MPI-TS  
FC=gfortran    
Singularity image 
oras://ghcr.io/edoapra/nwchem/nwchem-dev.mpi-ts.ompi41x:20230710_233358

The hotfix/release-7-2-0 branch is not affected by this bug
[pspw_md.output.239354.txt](https://github.com/nwchemgit/nwchem/files/12017530/pspw_md.output.239354.txt)

**Attach log files**
```
diff -u pspw_md.ok.out.nwparse pspw_md.out.nwparse
--- pspw_md.ok.out.nwparse	2023-07-11 03:28:56.000000000 -0700
+++ pspw_md.out.nwparse	2023-07-11 03:28:56.000000000 -0700
@@ -1,13 +1,13 @@
 Effective nuclear repulsion energy (a.u.) 85.91
-Total PSPW energy : -13.56964
+Total PSPW energy : nan
 == 0.000 0.000 0.000 
-Total PSPW energy : -13.74176
+Total PSPW energy : nan
 == 0.000 0.000 0.000 
-Total PSPW energy : -13.74176
+Total PSPW energy : nan
 == 0.000 0.000 0.000 
-Total PSPW energy : -14.32395
+Total PSPW energy : nan
 Effective nuclear repulsion energy (a.u.) 85.91
-Total PSPW energy : -14.27678
-Total PSPW energy : -14.33590
-Total PSPW energy : -14.25267
-Total PSPW energy : -14.38971
+Total PSPW energy : nan
+Total PSPW energy : nan
+Total PSPW energy : nan
+Total PSPW energy : nan
```

**Comment by ebylaska** [comment]
Ok, I'll try to figure out a fix.

**Comment by edoapra** [comment]
Commit https://github.com/nwchemgit/nwchem/commit/3355e82837b6a0476426fb8bc54d2428014fea58 fixes this issue

**Comment by edoapra** [comment]
Unfortunately, the bug is still present in the master branch at this time

**Comment by ebylaska** [comment]
I fixed another bug I found while working on this...Hopefully, have a solution soon.

**Comment by edoapra** [comment]
Bug still present after commit https://github.com/nwchemgit/nwchem/commit/ffb59dde8dafc49b3ec1c247d0e288901301078f

**Comment by edoapra** [comment]
This bug is present both in master and hotfix/release-7-2-0.  
 
Disabling OpenMP makes the pspw_md QA run to completion correctly.
